spring:
  application:
    name: time-eureka
server:
  port: 8090
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8090/eureka/

